expr = lambda variable space unboundVariable

lambda = "l" variable applyOrSpace
space = " "
applyOrSpace = "." | space

(* Every letter except 'l' for 'lambda' *)
variable =  "a" | "b" | "c" | "d" | "e" |
            "f" | "g" | "h" | "i" | "j" |
            "k" |       "m" | "n" | "o" |
            "p" | "q" | "r" | "s" | "t" |
            "u" | "v" | "w" | "x" | "y" | "z"
openParen = "("
closeParen = ")"

unboundVariable = openParen variable closeParen
