expr = lambda variable space unboundVariable

lambda = "l" variable applyOrSpace
space = " "
applyOrSpace = "." | space

(*TODO: add rest of alphabet except 'l'*)
variable = "x" | "y"
openParen = "("
closeParen = ")"

unboundVariable = openParen variable closeParen
